module WriteScheme.Tests.CoreTest

open Xunit
open FsUnit.Xunit

let rep = WriteScheme.Repl.rep WriteScheme.Builtin.builtin

[<Fact>]
let ``eqv?`` () =
    "(eqv? 'a 'a)" |> rep |> should equal "#t"
    "(eqv? 'a 'b)" |> rep |> should equal "#f"
    "(eqv? ''a ''a)" |> rep |> should equal "#t"
    "(eqv? ''a ''b)" |> rep |> should equal "#f"
    "(eqv? ',1 ',1)" |> rep |> should equal "#t"
    "(eqv? ',1 ',2)" |> rep |> should equal "#f"
    "(eqv? 2 2)" |> rep |> should equal "#t"
    "(eqv? 2 3)" |> rep |> should equal "#f"
    "(eqv? 1/3 1/3)" |> rep |> should equal "#t"
    "(eqv? 1/3 2/3)" |> rep |> should equal "#f"
    "(eqv? 1/3 1/2)" |> rep |> should equal "#f"
    "(eqv? 2/4 1/2)" |> rep |> should equal "#t"
    "(eqv? 4/2 2)" |> rep |> should equal "#t"
    "(eqv? 1.5 1.5)" |> rep |> should equal "#t"
    "(eqv? 1.5 2.5)" |> rep |> should equal "#f"
    "(eqv? 3/2 1.5)" |> rep |> should equal "#f"
    "(eqv? 1+2i 1+2i)" |> rep |> should equal "#t"
    "(eqv? 1+2i 1+3i)" |> rep |> should equal "#f"
    "(eqv? 1.3-2.5i 1.3-2.5i)" |> rep |> should equal "#t"
    "(eqv? 1.3+0i 1.3)" |> rep |> should equal "#f"
    "(eqv? #t #t)" |> rep |> should equal "#t"
    "(eqv? #t #f)" |> rep |> should equal "#f"
    "(eqv? #f 'nil)" |> rep |> should equal "#f"
    "(eqv? '(a) '(a))" |> rep |> should equal "#f"
    "(eqv? '(a (b) c) '(a (b) c))" |> rep |> should equal "#f"
    "(eqv? '(1 . 2) '(1 . 2))" |> rep |> should equal "#f"
    "(eqv? '(1 2 . 3) '(1 2 . 3))" |> rep |> should equal "#f"
    "(eqv? #\\a #\\a)" |> rep |> should equal "#t"
    "(eqv? #\\a #\\b)" |> rep |> should equal "#f"
    "(eqv? \"abc\" \"abc\")" |> rep |> should equal "#f"
    "(eqv? 1 \"1\")" |> rep |> should equal "#f"
    "(eqv? '#(1 2 3) '#(1 2 3))" |> rep |> should equal "#f"
    "(eqv? #u8(1 2 3) #u8(1 2 3))" |> rep |> should equal "#f"
    "(eqv? (values 1 2) (values 1 2))" |> rep |> should equal "#f"
    "(let ((p \"a\")) (eqv? p p))" |> rep |> should equal "#t"
    "(eqv? '() '())" |> rep |> should equal "#t"
    "(eqv? (cons 1 2) (cons 1 2))" |> rep |> should equal "#f"
    "(eqv? (lambda () 1) (lambda () 1))" |> rep |> should equal "#f"
    "(let ((p (lambda (x) x))) (eqv? p p))" |> rep |> should equal "#t"

[<Fact>]
let ``equal?`` () =
    "(equal? 'a 'a)" |> rep |> should equal "#t"
    "(equal? 'a 'b)" |> rep |> should equal "#f"
    "(equal? ''a ''a)" |> rep |> should equal "#t"
    "(equal? ''a ''b)" |> rep |> should equal "#f"
    "(equal? ',1 ',2)" |> rep |> should equal "#f"
    "(equal? ',1 ',1)" |> rep |> should equal "#t"
    "(equal? 2 2)" |> rep |> should equal "#t"
    "(equal? 3 2)" |> rep |> should equal "#f"
    "(equal? 1/3 1/3)" |> rep |> should equal "#t"
    "(equal? 1/3 2/3)" |> rep |> should equal "#f"
    "(equal? 1/3 1/2)" |> rep |> should equal "#f"
    "(equal? 2/4 1/2)" |> rep |> should equal "#t"
    "(equal? 4/2 2)" |> rep |> should equal "#t"
    "(equal? 1.5 1.5)" |> rep |> should equal "#t"
    "(equal? 1.5 2.5)" |> rep |> should equal "#f"
    "(equal? 3/2 1.5)" |> rep |> should equal "#f"
    "(equal? 1+2i 1+2i)" |> rep |> should equal "#t"
    "(equal? 1+2i 1+3i)" |> rep |> should equal "#f"
    "(equal? 1.3-2.5i 1.3-2.5i)" |> rep |> should equal "#t"
    "(equal? 1.3+0i 1.3)" |> rep |> should equal "#f"
    "(equal? #t #t)" |> rep |> should equal "#t"
    "(equal? #t #f)" |> rep |> should equal "#f"
    "(equal? #f 'nil)" |> rep |> should equal "#f"
    "(equal? '(a) '(a))" |> rep |> should equal "#t"
    "(equal? 'a '(a))" |> rep |> should equal "#f"
    "(equal? '(a (b) c) '(a (b) c))" |> rep |> should equal "#t"
    "(equal? '(a b c) '(a (b) c))" |> rep |> should equal "#f"
    "(equal? '(1 2) '(1 2 3))" |> rep |> should equal "#f"
    "(equal? '(1 . 2) '(1 . 2))" |> rep |> should equal "#t"
    "(equal? '(1 . 2) '(1 . 3))" |> rep |> should equal "#f"
    "(equal? '(1 2 . 3) '(1 2 . 3))" |> rep |> should equal "#t"
    "(equal? '(1 2 . 3) '(1 2 . 4))" |> rep |> should equal "#f"
    "(equal? '(1 . 2) '(1 3 . 2))" |> rep |> should equal "#f"
    "(equal? '(1 2 . 3) '(1 . 3))" |> rep |> should equal "#f"
    "(equal? #\\a #\\a)" |> rep |> should equal "#t"
    "(equal? #\\a #\\b)" |> rep |> should equal "#f"
    "(equal? \"abc\" \"abc\")" |> rep |> should equal "#t"
    "(equal? \"a\" \"abc\")" |> rep |> should equal "#f"
    "(equal? 1 \"1\")" |> rep |> should equal "#f"
    "(equal? '#(1 2 3) '#(1 2 3))" |> rep |> should equal "#t"
    "(equal? '#(1 2 3) '#(1 2 4))" |> rep |> should equal "#f"
    "(equal? '#(1 2) '#(1 2 3))" |> rep |> should equal "#f"
    "(equal? #u8(1 2 3) #u8(1 2 3))" |> rep |> should equal "#t"
    "(equal? #u8(1 2 3) #u8(1 2 4))" |> rep |> should equal "#f"
    "(equal? #u8() #u8())" |> rep |> should equal "#t"
    "(equal? #u8(1) #u8(1 2))" |> rep |> should equal "#f"
    "(equal? #u8(1 2) #u8(1 2 3))" |> rep |> should equal "#f"
    "(equal? #u8(1 2) #u8(1 3))" |> rep |> should equal "#f"
    "(equal? (values 1 2) (values 1 2))" |> rep |> should equal "#t"
    "(equal? (values 1 2) (values 1 3))" |> rep |> should equal "#f"
    "(equal? (values 1 2) (values 1 2 3))" |> rep |> should equal "#f"
    "(let ((p \"a\")) (equal? p p))" |> rep |> should equal "#t"
    "(equal? '() '())" |> rep |> should equal "#t"
    "(equal? (cons 1 2) (cons 1 2))" |> rep |> should equal "#t"
    "(equal? (lambda () 1) (lambda () 1))" |> rep |> should equal "#f"
    "(let ((p (lambda (x) x))) (equal? p p))" |> rep |> should equal "#t"

[<Fact>]
let ``not`` () =
    "(not #t)" |> rep |> should equal "#f"
    "(not 3)" |> rep |> should equal "#f"
    "(not (list 3))" |> rep |> should equal "#f"
    "(not #f)" |> rep |> should equal "#t"
    "(not '())" |> rep |> should equal "#f"
    "(not (list))" |> rep |> should equal "#f"
    "(not 'nil)" |> rep |> should equal "#f"

[<Fact>]
let ``boolean?`` () =
    "(boolean? #f)" |> rep |> should equal "#t"
    "(boolean? #t)" |> rep |> should equal "#t"
    "(boolean? 0)" |> rep |> should equal "#f"
    "(boolean? '())" |> rep |> should equal "#f"
