module WriteScheme.Tests.LiteralTest

open Xunit
open FsUnit.Xunit

let rep = WriteScheme.Repl.rep WriteScheme.Builtin.builtin

[<Fact>]
let number () =
    "0" |> rep |> should equal "0"
    "1" |> rep |> should equal "1"
    "+1" |> rep |> should equal "1"
    "-1" |> rep |> should equal "-1"
    "1.0" |> rep |> should equal "1"
    "1." |> rep |> should equal "1"
    "0.1" |> rep |> should equal "0.1"
    ".1" |> rep |> should equal "0.1"
    "-100.0e-3" |> rep |> should equal "-0.1"
    "-0.1" |> rep |> should equal "-0.1"
    "-.1" |> rep |> should equal "-0.1"
    "100.0e-3" |> rep |> should equal "0.1"
    "1e2" |> rep |> should equal "100"
    "1.0E2" |> rep |> should equal "100"
    "1.0e+2" |> rep |> should equal "100"
    "+nan.0" |> rep |> should equal "+nan.0"
    "+NaN.0" |> rep |> should equal "+nan.0"
    "-nan.0" |> rep |> should equal "+nan.0"
    "+inf.0" |> rep |> should equal "+inf.0"
    "+Inf.0" |> rep |> should equal "+inf.0"
    "-inf.0" |> rep |> should equal "-inf.0"
    "-INF.0" |> rep |> should equal "-inf.0"
    "1/2" |> rep |> should equal "1/2"
    "1/3" |> rep |> should equal "1/3"
    "3/6" |> rep |> should equal "1/2"
    "10/2" |> rep |> should equal "5"
    "-1/2" |> rep |> should equal "-1/2"
    "0/2" |> rep |> should equal "0"
    "1+2i" |> rep |> should equal "1+2i"
    "1+2I" |> rep |> should equal "1+2i"
    "+1-2i" |> rep |> should equal "1-2i"
    "1.5-2.5i" |> rep |> should equal "1.5-2.5i"
    "1+i" |> rep |> should equal "1+1i"
    "1-i" |> rep |> should equal "1-1i"
    "2i" |> rep |> should equal "0+2i"
    "-2.5i" |> rep |> should equal "0-2.5i"
    "1/2+3/4i" |> rep |> should equal "0.5+0.75i"
    "+i" |> rep |> should equal "0+1i"
    "-i" |> rep |> should equal "0-1i"
    "+inf.0+nan.0i" |> rep |> should equal "+inf.0+nan.0i"
    "3.0@0" |> rep |> should equal "3+0i"
    "#x11" |> rep |> should equal "17"
    "#X11" |> rep |> should equal "17"
    "#xA" |> rep |> should equal "10"
    "#Xf" |> rep |> should equal "15"
    "#x-10" |> rep |> should equal "-16"
    "#x10/2" |> rep |> should equal "8"
    "#x11/2" |> rep |> should equal "17/2"
    "#x1+i" |> rep |> should equal "1+1i"
    "#x+i" |> rep |> should equal "0+1i"
    "#x-i" |> rep |> should equal "0-1i"
    "#x10+10i" |> rep |> should equal "16+16i"
    "#x10@0" |> rep |> should equal "16+0i"
    "#d11" |> rep |> should equal "11"
    "#D11" |> rep |> should equal "11"
    "#d-10" |> rep |> should equal "-10"
    "#d1." |> rep |> should equal "1"
    "#d.1" |> rep |> should equal "0.1"
    "#d11/2" |> rep |> should equal "11/2"
    "#o11" |> rep |> should equal "9"
    "#O11" |> rep |> should equal "9"
    "#o7" |> rep |> should equal "7"
    "#o-10" |> rep |> should equal "-8"
    "#o10/2" |> rep |> should equal "4"
    "#o11/2" |> rep |> should equal "9/2"
    "#o2-i" |> rep |> should equal "2-1i"
    "#b11" |> rep |> should equal "3"
    "#B11" |> rep |> should equal "3"
    "#b-10" |> rep |> should equal "-2"
    "#b10/10" |> rep |> should equal "1"
    "#b11/10" |> rep |> should equal "3/2"
    "#e1.0" |> rep |> should equal "1"
    "#e#x10" |> rep |> should equal "16"
    "#e#x10@0" |> rep |> should equal "16"
    "#e1" |> rep |> should equal "1"
    "#e1.0" |> rep |> should equal "1"
    "#e1+2i" |> rep |> should equal "1"
    "#i1" |> rep |> should equal "1"
    "#x#i10" |> rep |> should equal "16"
    "#i#x10" |> rep |> should equal "16"
    "#i1" |> rep |> should equal "1"
    "#i1.0" |> rep |> should equal "1"
    "#i1+2i" |> rep |> should equal "1+2i"

[<Fact>]
let bool () =
    "#t" |> rep |> should equal "#t"
    "#T" |> rep |> should equal "#t"
    "#true" |> rep |> should equal "#t"
    "#TRUE" |> rep |> should equal "#t"
    "#f" |> rep |> should equal "#f"
    "#F" |> rep |> should equal "#f"
    "#false" |> rep |> should equal "#f"
    "#FALSE" |> rep |> should equal "#f"

[<Fact>]
let ``pair and list`` () =
    "'()" |> rep |> should equal "()"
    "'(1 2 3)" |> rep |> should equal "(1 2 3)"
    "'(1 (2) 3)" |> rep |> should equal "(1 (2) 3)"
    "'(1 . 2)" |> rep |> should equal "(1 . 2)"
    "'(1 2 . 3)" |> rep |> should equal "(1 2 . 3)"
    "'(1 2 . (3 4))" |> rep |> should equal "(1 2 3 4)"
    "'(1 . (2 . (3 . ())))" |> rep |> should equal "(1 2 3)"
    "'(1 . (2 . 3))" |> rep |> should equal "(1 2 . 3)"
    "'(1 2 . (3 . (4 . ())))" |> rep |> should equal "(1 2 3 4)"
    "'(1 #t \"a\")" |> rep |> should equal "(1 #t \"a\")"
    "'(a 'b)" |> rep |> should equal "(a 'b)"
    "'(  1   2  )" |> rep |> should equal "(1 2)"
    "'`(a ,b ,@c)" |> rep |> should equal "`(a ,b ,@c)"

[<Fact>]
let symbol () =
    "'..." |> rep |> should equal "..."
    "'+" |> rep |> should equal "+"
    "'+soup+" |> rep |> should equal "+soup+"
    "'->string" |> rep |> should equal "->string"
    "'<=?" |> rep |> should equal "<=?"
    "'a34kTMNs" |> rep |> should equal "a34kTMNs"
    "'lambda" |> rep |> should equal "lambda"
    "'list->vector" |> rep |> should equal "list->vector"
    "'q" |> rep |> should equal "q"
    "'V17a" |> rep |> should equal "V17a"
    "'|two words|" |> rep |> should equal "two words"
    "'|two\\x20;words|" |> rep |> should equal "two words"
    "'|a\\\\b|" |> rep |> should equal "a\\b"
    "'|a\\nb|" |> rep |> should equal "a\nb"
    "'|a\\vb|" |> rep |> should equal "a\u000bb"
    "'|a\\fb|" |> rep |> should equal "a\u000cb"
    "'+.a" |> rep |> should equal "+.a"
    "'-.a" |> rep |> should equal "-.a"
    "'.a" |> rep |> should equal ".a"

    "'the-word-recursion-has-many-meanings"
    |> rep
    |> should equal "the-word-recursion-has-many-meanings"

[<Fact>]
let char () =
    "#\\a" |> rep |> should equal "#\\a"
    "#\\x41" |> rep |> should equal "#\\A"
    "#\\X41" |> rep |> should equal "#\\A"
    "#\\x0041" |> rep |> should equal "#\\A"
    "#\\(" |> rep |> should equal "#\\("
    "#\\)" |> rep |> should equal "#\\)"
    "#\\\"" |> rep |> should equal "#\\\""
    "#\\\\" |> rep |> should equal "#\\\\"
    "#\\x1f" |> rep |> should equal "#\\x1f"
    "#\\x1F" |> rep |> should equal "#\\x1f"
    "#\\alarm" |> rep |> should equal "#\\alarm"
    "#\\aLaRm" |> rep |> should equal "#\\alarm"
    "#\\Alarm" |> rep |> should equal "#\\alarm"
    "#\\backspace" |> rep |> should equal "#\\backspace"
    "#\\Backspace" |> rep |> should equal "#\\backspace"
    "#\\delete" |> rep |> should equal "#\\delete"
    "#\\Delete" |> rep |> should equal "#\\delete"
    "#\\escape" |> rep |> should equal "#\\escape"
    "#\\Escape" |> rep |> should equal "#\\escape"
    "#\\newline" |> rep |> should equal "#\\newline"
    "#\\Newline" |> rep |> should equal "#\\newline"
    "#\\null" |> rep |> should equal "#\\null"
    "#\\Null" |> rep |> should equal "#\\null"
    "#\\return" |> rep |> should equal "#\\return"
    "#\\Return" |> rep |> should equal "#\\return"
    "#\\space" |> rep |> should equal "#\\ "
    "#\\Space" |> rep |> should equal "#\\ "
    "#\\tab" |> rep |> should equal "#\\tab"
    "#\\Tab" |> rep |> should equal "#\\tab"

[<Fact>]
let string () =
    "\"\"" |> rep |> should equal "\"\""
    "\"12345\"" |> rep |> should equal "\"12345\""
    "\"hello\\\"world\"" |> rep |> should equal "\"hello\\\"world\""
    "\"\\x3a;\"" |> rep |> should equal "\":\""
    "\"\\X3A;\"" |> rep |> should equal "\":\""
    "\"\\x003A;\"" |> rep |> should equal "\":\""
    "\"\\x3071;\"" |> rep |> should equal "\"ぱ\""
    "\"\\x1F600;\"" |> rep |> should equal "\"😀\""
    "\"foo\\ \n  bar\"" |> rep |> should equal "\"foobar\""
    "\"a\\vb\"" |> rep |> should equal "\"a\u000bb\""
    "\"a\\fb\"" |> rep |> should equal "\"a\u000cb\""

    "\"1\\a2\\b3\\t4\\n5\\r6\\\"7\\\\8|90\""
    |> rep
    |> should equal "\"1\a2\b3\t4\n5\r6\\\"7\\8|90\""

[<Fact>]
let vector () =
    "#()" |> rep |> should equal "#()"
    "#(1 2 3)" |> rep |> should equal "#(1 2 3)"
    "#(0 10 5)" |> rep |> should equal "#(0 10 5)"
    "#(\"a\" \"b\" \"c\")" |> rep |> should equal "#(\"a\" \"b\" \"c\")"
    "#(a b c)" |> rep |> should equal "#(a b c)"
    "'#(1 2)" |> rep |> should equal "#(1 2)"
    "#(  1   2   )" |> rep |> should equal "#(1 2)"
    "#(1 #(2) 3)" |> rep |> should equal "#(1 #(2) 3)"
    "#(1 'a 2)" |> rep |> should equal "#(1 'a 2)"

[<Fact>]
let bytevector () =
    "#u8()" |> rep |> should equal "#u8()"
    "#u8(1 2 3)" |> rep |> should equal "#u8(1 2 3)"
    "#u8(0 10 5)" |> rep |> should equal "#u8(0 10 5)"
    "#u8(255)" |> rep |> should equal "#u8(255)"
    "#u8(#x10 #o10 #b10)" |> rep |> should equal "#u8(16 8 2)"
    "'#u8(1 2)" |> rep |> should equal "#u8(1 2)"
    "#U8(1 2)" |> rep |> should equal "#u8(1 2)"
    "#u8(  1   2   )" |> rep |> should equal "#u8(1 2)"
    (fun () -> "#u8(256)" |> rep |> ignore) |> should throw typeof<System.Exception>
    (fun () -> "#u8(-1)" |> rep |> ignore) |> should throw typeof<System.Exception>
    (fun () -> "#u8(1.0)" |> rep |> ignore) |> should throw typeof<System.Exception>

    (fun () -> "#u8(1+2i)" |> rep |> ignore)
    |> should throw typeof<System.Exception>

[<Fact>]
let ``comments`` () =
    "; comment\n1" |> rep |> should equal "1"
    "#| block comment |# 42" |> rep |> should equal "42"
