namespace WriteScheme

open Type
open WriteScheme.Builtins

module Builtin =
    let builtin =
        Context.extendEnvs
            Context.empty
            [ "quote", SSyntax sQuote |> ref
              "lambda", SSyntax sLambda |> ref
              "if", SSyntax sIf |> ref
              "set!", SSyntax sSet |> ref
              "cond", SSyntax sCond |> ref
              "case", SSyntax sCase |> ref
              "and", SSyntax sAnd |> ref
              "or", SSyntax sOr |> ref
              "when", SSyntax sWhen |> ref
              "unless", SSyntax sUnless |> ref
              "let", SSyntax sLet |> ref
              "let*", SSyntax sLetStar |> ref
              "letrec", SSyntax sLetRec |> ref
              "letrec*", SSyntax sLetRecStar |> ref
              "let-values", SSyntax sLetValues |> ref
              "let*-values", SSyntax sLetStarValues |> ref
              "begin", SSyntax sBegin |> ref
              "do", SSyntax sDo |> ref
              "delay", SSyntax sDelay |> ref
              "delay-force", SSyntax sDelayForce |> ref
              "parameterize", SSyntax sParameterize |> ref
              "guard", SSyntax sGuard |> ref
              "let-syntax", SSyntax sLetSyntax |> ref
              "letrec-syntax", SSyntax sLetRecSyntax |> ref
              "quasiquote", SSyntax sQuasiquote |> ref
              "syntax-rules", SSyntax sSyntaxRules |> ref
              "syntax-error", SSyntax sSyntaxError |> ref
              "define", SSyntax sDefine |> ref
              "define-values", SSyntax sDefineValues |> ref
              "define-syntax", SSyntax sDefineSyntax |> ref
              "define-record-type", SSyntax sDefineRecordType |> ref
              "force", SProcedure sForce |> ref
              "promise?", SProcedure isPromise |> ref
              "make-promise", SProcedure sMakePromise |> ref
              "make-parameter", SProcedure sMakeParameter |> ref
              "eqv?", SProcedure isEqv |> ref
              "eq?", SProcedure isEqv |> ref
              "equal?", SProcedure isEqual |> ref
              "number?", SProcedure isNumber |> ref
              "complex?", SProcedure isComplex |> ref
              "real?", SProcedure isReal |> ref
              "rational?", SProcedure isRational |> ref
              "integer?", SProcedure isInteger |> ref
              "exact?", SProcedure isExact |> ref
              "inexact?", SProcedure isInexact |> ref
              "exact-integer?", SProcedure isExactInteger |> ref
              "finite?", SProcedure isFinite |> ref
              "infinite?", SProcedure isInfinite |> ref
              "nan?", SProcedure isNaN |> ref
              "=", SProcedure equalNumber |> ref
              "<", SProcedure lessNumber |> ref
              ">", SProcedure greaterNumber |> ref
              "<=", SProcedure lessEqualNumber |> ref
              ">=", SProcedure greaterEqualNumber |> ref
              "zero?", SProcedure isZero |> ref
              "positive?", SProcedure isPositive |> ref
              "negative?", SProcedure isNegative |> ref
              "odd?", SProcedure isOdd |> ref
              "even?", SProcedure isEven |> ref
              "+", SProcedure addNumber |> ref
              "*", SProcedure multiplyNumber |> ref
              "-", SProcedure subtractNumber |> ref
              "/", SProcedure divideNumber |> ref
              "make-rectangular", SProcedure sMakeRectangular |> ref
              "make-polar", SProcedure sMakePolar |> ref
              "real-part", SProcedure sRealPart |> ref
              "imag-part", SProcedure sImagPart |> ref
              "magnitude", SProcedure sMagnitude |> ref
              "angle", SProcedure sAngle |> ref
              "number->string", SProcedure sNumberToString |> ref
              "string->number", SProcedure sStringToNumber |> ref
              "not", SProcedure sNot |> ref
              "boolean?", SProcedure isBoolean |> ref
              "pair?", SProcedure isPair |> ref
              "cons", SProcedure sCons |> ref
              "car", SProcedure sCar |> ref
              "cdr", SProcedure sCdr |> ref
              "null?", SProcedure isNull |> ref
              "list?", SProcedure isList |> ref
              "list", SProcedure sList |> ref
              "append", SProcedure sAppend |> ref
              "symbol?", SProcedure isSymbol |> ref
              "symbol=?", SProcedure isSymbolEq |> ref
              "symbol->string", SProcedure sSymbolToString |> ref
              "string->symbol", SProcedure sStringToSymbol |> ref
              "char?", SProcedure isChar |> ref
              "string?", SProcedure isString |> ref
              "make-string", SProcedure sMakeString |> ref
              "string", SProcedure sString |> ref
              "string-length", SProcedure sStringLength |> ref
              "string-ref", SProcedure sStringRef |> ref
              "string=?", SProcedure sStringEq |> ref
              "string<?", SProcedure sStringLt |> ref
              "string>?", SProcedure sStringGt |> ref
              "string<=?", SProcedure sStringLe |> ref
              "string>=?", SProcedure sStringGe |> ref
              "string-ci=?", SProcedure sStringCiEq |> ref
              "string-ci<?", SProcedure sStringCiLt |> ref
              "string-ci>?", SProcedure sStringCiGt |> ref
              "string-ci<=?", SProcedure sStringCiLe |> ref
              "string-ci>=?", SProcedure sStringCiGe |> ref
              "string-upcase", SProcedure sStringUpcase |> ref
              "string-downcase", SProcedure sStringDowncase |> ref
              "string-foldcase", SProcedure sStringFoldcase |> ref
              "substring", SProcedure sSubstring |> ref
              "string-append", SProcedure sStringAppend |> ref
              "string->list", SProcedure sStringToList |> ref
              "list->string", SProcedure sListToString |> ref
              "string-copy", SProcedure sStringCopy |> ref
              "vector?", SProcedure isVector |> ref
              "make-vector", SProcedure sMakeVector |> ref
              "vector", SProcedure sVector |> ref
              "vector-length", SProcedure sVectorLength |> ref
              "vector-ref", SProcedure sVectorRef |> ref
              "vector-set!", SProcedure sVectorSet |> ref
              "vector->list", SProcedure sVectorToList |> ref
              "list->vector", SProcedure sListToVector |> ref
              "vector-fill!", SProcedure sVectorFill |> ref
              "bytevector?", SProcedure isByteVector |> ref
              "make-bytevector", SProcedure sMakeByteVector |> ref
              "bytevector", SProcedure sByteVector |> ref
              "bytevector-length", SProcedure sByteVectorLength |> ref
              "bytevector-u8-ref", SProcedure sByteVectorU8Ref |> ref
              "bytevector-u8-set!", SProcedure sByteVectorU8Set |> ref
              "bytevector-copy", SProcedure sByteVectorCopy |> ref
              "string->utf8", SProcedure sStringToUtf8 |> ref
              "utf8->string", SProcedure sUtf8ToString |> ref
              "procedure?", SProcedure isProcedure |> ref
              "apply", SProcedure sApply |> ref
              "map", SProcedure sMap |> ref
              "for-each", SProcedure sForEach |> ref
              "call-with-current-continuation", SProcedure sCallCC |> ref
              "call/cc", SProcedure sCallCC |> ref
              "values", SProcedure sValues |> ref
              "call-with-values", SProcedure sCallWithValues |> ref
              "dynamic-wind", SProcedure sDynamicWind |> ref
              "with-exception-handler", SProcedure sWithExceptionHandler |> ref
              "raise", SProcedure sRaise |> ref
              "error", SProcedure sError |> ref
              "error-object?", SProcedure isErrorObject |> ref
              "error-object-message", SProcedure sErrorObjectMessage |> ref
              "error-object-irritants", SProcedure sErrorObjectIrritants |> ref
              "display", SProcedure sDisplay |> ref
              "load", SProcedure sLoad |> ref ]
